name: Deploy to Power BI Service

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name == 'develop' && 'development' || 'staging' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Instalar .NET y pbi-tools
      run: |
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.0
        dotnet tool install --global PbiTools

    - name: Autenticarse con Azure (Service Principal)
      run: |
        export PBITOOLS_CLIENTID=${{ secrets.POWERBI_CLIENT_ID }}
        export PBITOOLS_CLIENTSECRET=${{ secrets.POWERBI_CLIENT_SECRET }}
        export PBITOOLS_TENANTID=${{ secrets.POWERBI_TENANT_ID }}

    - name: Determinar Workspace
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "WORKSPACE_ID=${{ secrets.PROD_WORKSPACE_ID }}" >> $GITHUB_ENV
        elif [[ "${{ github.ref_name }}" == "develop" ]]; then
          echo "WORKSPACE_ID=${{ secrets.DEV_WORKSPACE_ID }}" >> $GITHUB_ENV
        else
          echo "WORKSPACE_ID=${{ secrets.STAGING_WORKSPACE_ID }}" >> $GITHUB_ENV
        fi

    - name: Publicar PBIP a Power BI Service
      run: |
        pbi-tools push "Proyecto_Inteligencia De Negocios.pbip" \
          --workspace-id "$WORKSPACE_ID" \
          --deployment-mode CreateOrOverwrite
